leftnav:
- identifier: 90560c2e-fc27-4fa7-b020-9189c790a2aa
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 32fe390f-a792-4e31-8512-7e6ffbaacc9c
  name: Calendar
  url: /pages/calendar
  weight: 20
